sonar.projectKey=pede-logo-catalogo
sonar.organization=pedelogo
sonar.projectName=PedeLogo Catalogo

# Onde está o código fonte
sonar.sources=src/PedeLogo.Catalogo.Api

# Onde estão os testes
sonar.tests=tests/PedeLogo.Catalogo.UnitTests

# Coverage
sonar.cs.opencover.reportsPaths=**/TestResults/**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/TestResults/*.trx

# Exclusões
sonar.coverage.exclusions=**/Migrations/**,**/Program.cs,**/Startup.cs

# Encoding
sonar.sourceEncoding=UTF-8