apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-data-base
  namespace: data-base
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["mongodb-secret"]
  #- apiGroups: ["apps"]
  # resources: ["statefullset"]
  # verbs: ["get", "list"]
