apiVersion: v1
kind: Secret
metadata:
  name: catalogo-secret
type: Opaque
data:
  Mongo__host: bW9uZ28tc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  Mongo__port: MjcwMTc=
  Mongo__DataBase: YWRtaW4=
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29wd2Q=
