apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: gateway
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.160.0
  env:
    - name: MONGO_USER
      valueFrom: { secretKeyRef: { name: catalogo-secret, key: MONGO_INITDB_ROOT_USERNAME } }
    - name: MONGO_PASSWORD
      valueFrom: { secretKeyRef: { name: catalogo-secret, key: MONGO_INITDB_ROOT_PASSWORD } }
  config:
    receivers:
      otlp:
        protocols:
          grpc: { endpoint: 0.0.0.0:4317 }
          http: { endpoint: 0.0.0.0:4318 }
      k8s_cluster:
        collection_interval: 30s
      mongodb:
        hosts:
          - endpoint: mongo-service.default.svc.cluster.local:27017
        username: ${env:MONGO_USER}
        password: ${env:MONGO_PASSWORD}
        collection_interval: 60s
        tls:
          insecure: true
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch: {}
    exporters:
      debug: { verbosity: basic }
      prometheus:
        endpoint: 0.0.0.0:8889
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp, k8s_cluster, mongodb]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]