name: App CD

on: 
  workflow_call:
    
jobs:
  app_cd:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: download docker image
        run: |
          docker pull ghcr.io/${{ github.repository }}/catalogo-api:${{ github.sha }}

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ vars.REGION }} 

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ${{ vars.REGION }} \
            --name ${{ vars.CLUSTER_NAME }}
      
      - uses: Azure/k8s-deploy@v7
        with:
          manifests: |
            k8s/cadastro-k8s/cadastro.yaml
            k8s/cadastro-k8s/secret-cadastro.yaml
            k8s/cadastro-k8s/configmap.yaml
            k8s/cadastro-k8s/service-cadastro.yaml
            k8s/cadastro-k8s/hpa-cadastro.yaml
            k8s/mongodb-k8s/mongodb.yaml
            k8s/mongodb-k8s/secret-mongodb.yaml
            k8s/mongodb-k8s/service-mongodb.yaml
            k8s/mongodb-k8s/hpa-mongodb.yaml
          images: |
            ghcr.io/${{ github.repository }}/catalogo-api:${{ github.sha }}