name: dotnet-build

on:
  pull_request:
    branches: [main]
    paths: ["**/src/*.*"]

  push:
    branches:
      - staging
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "infra/**/*.md"
      - "src/**/*.md"
      - "**/*.yaml"

permissions:
  contents: read
  pull-requests: write
  security-events: write
  id-token: write

jobs:
  # ────────────────────────────────────────────────────────────────
  # ETAPA 1 — Build e Testes
  #
  # ────────────────────────────────────────────────────────────────
  build:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup .NET build
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore PedeLogo.Catalogo.sln

      - name: instlar sonar-scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: sonar begin
        run: |
          dotnet sonarscanner begin \
            /k:"${{ secrets.SONAR_PROJECT_KEY }}" \
            /o:"${{ secrets.SONAR_ORGANIZATION }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="./TestResults/**/coverage.opencover.xml"

      - name: Build
        run: dotnet build PedeLogo.Catalogo.sln --configuration Release --no-restore

      - name: Testes Unitários
        run: |
          dotnet test tests/PedeLogo.Catalogo.UnitTests \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=unit-results.trx" \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Sonar End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"

  tests_integration:
    name: Testes de Integração
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4.0
        ports:
          - 27017:27017

        options: >-
          --health-cmd "mongo --eval 'db.adminCommand({ ping: 1 })'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Setup .NET build
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Testes de Integração
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        run: |
          dotnet test tests/PedeLogo.Catalogo.IntegrationTests \
          --configuration Release \
          --no-build \
          --logger "console;verbosity=detailed" \
          --logger "trx;LogFileName=integration-results.trx" \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          --verbosity normal

  ############################################################
  # ETAPA 2 — Build e Push da Imagem Docker

  ############################################################

  docker_build_and_push:
    name: Build e Push da Imagem Docker
    runs-on: ubuntu-latest
    needs: [build, tests_integration]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.DOCKER_token }}

      - name: Upload de Imagem para Docker Hub
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./src/PedeLogo.Catalogo.Api/Dockerfile
          push: true
          tags: ${{ secrets.docker_user }}/catalogo:latest, ${{ secrets.docker_user }}/catalogo:${{ github.sha }}

  #################################################################
  # ETAPA 3 — Publicação na was eks
  #
  #################################################################

  eks_deploy:
    name: Deploy na AWS EKS
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.DOCKER_token }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-assume-role: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ vars.REGION }}

      - name: kubeconfig
        run: aws eks update-kubeconfig \
          --name ${{ vars.CLUSTER_NAME }} \
          --region ${{ vars.REGION }}

      - name: eks deploy
        run: |
          kubectl apply -f ./k8s -R
