name: Infrastructure CI

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'  
      
jobs:
  terraform:
    name: Terraform Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform fmt
        run: terraform fmt -check    

      - name: scan Linter
        uses: devops-infra/action-tflint@v1.0.5
        with:
          dir_filter: ./infra
            

              