name: Infrastructure CD

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 
        type: choice
        options:
          - dev
          - staging
          - prod