name: "Terraform"

on:
  push:
    branches: ["main"]
    #paths: ["src/terraform/**"]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    #environment: production
    permissions:
      id-token: write # obrigatório para solicitar o JWT OIDC
      contents: read

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      - name: configura aws credencial
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # AWS Region, e.g. us-east-2
          aws-region: ${{vars.REGION}}
          # The Amazon Resource Name (ARN) of the role to assume. Use the provided credentials to assume an IAM role and configure the Actions environment with the assumed role credentials rather than with the provided credentials.
          role-to-assume: ${{vars.AWS_ROLE}}

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        working-directory: ./src/terraform
        run: |
          terraform init \
          -backend-config="bucket=${{vars.BUCKET}}" \
          -backend-config="key=${{vars.KEY}}" \
          -backend-config="region=${{vars.REGION}}"

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        working-directory: ./src/terraform
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        working-directory: ./src/terraform
        run: terraform plan #-input=false

        # On push to "main", build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
        run: terraform apply -auto-approve #-input=false
