name: Test Cluster

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string

jobs:
  test-cluster:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ vars.REGION }}  
      - name: configura kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} \
          --region ${{ vars.REGION }}  
      - name: Test Cluster
        run: |
          kubectl get nodes    