name: Test Cluster

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      

jobs:
  test-cluster:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ vars.REGION }}  
      - name: configura kubeconfig
        env:
          CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
          REGION: ${{ vars.REGION }}
        run: |
          aws eks update-kubeconfig \
           --name "$CLUSTER_NAME" \
           --region "$REGION"
           
      - name: Validar o cluster
        run: |
          kubectl cluster-info
          kubectl get nodes -o wide
          kubectl get pods -A
          kubectl get pods -n kube-system

      - name: teste scheduler 
        run: |
          kubectl create deployment nginx-deploy \
          --image=nginx:alpine \
          --replicas=2
          kubectl wait \
          --for=condition=Ready \
          - l app: nginx-deploy \
          --timeout=120s
          kubectl get pod -l app=nginx-deploy -o wide  

      - name: teste de dns 
        run: |
          kubectl run dns-test \
          --image=busybox:1.36 \
          --restart=Never \
          -- sleep 300    
          kubectl exec dns-test -- nslookup kubernetes.default        